import Link from "next/link";
import Brand from "./Brand";

type Props = { url: string; setUrl: (value: string) => void; analyze: () => void; loading: boolean; error: string; progress: number; loadingStep: string };

export default function ResearchLanding({ url, setUrl, analyze, loading, error, progress, loadingStep }: Props) {
  return (
    <main className="premium-home">
      <header className="premium-nav"><Link href="/" aria-label="GTM Genome home"><Brand /></Link><nav aria-label="Main navigation"><a href="#method">The method</a><a href="https://github.com/Yashikaa07/gtm-genome" target="_blank" rel="noreferrer">Source ↗</a><Link href="/discover" className="nav-workspace">Open workspace <span>↗</span></Link></nav></header>
      <section className="premium-hero">
        <div className="hero-heading"><div className="eyebrow"><span className="live-dot" />GTM INTELLIGENCE, WITH CONTEXT</div><p className="hero-edition">RESEARCH / QUALIFY / ACT<br />A WORKSPACE BY YASHIKA HEMNANI</p></div>
        <div className="hero-layout"><div><h1>See the market.<br /><span className="hero-serif">Make your move.</span></h1><p className="hero-description">The intelligence between a company website and your next go-to-market decision. Built for people who turn research into revenue.</p></div><div className="hero-start"><p className="start-number">01 / START A NEW RESEARCH BRIEF</p><form onSubmit={(event) => { event.preventDefault(); if (!loading && url.trim()) analyze(); }}><label htmlFor="company-url">Company website</label><div className="premium-input"><span aria-hidden="true">↗</span><input id="company-url" inputMode="url" value={url} onChange={(event) => setUrl(event.target.value)} disabled={loading} placeholder="company.com" /><button disabled={loading || !url.trim()} aria-label={loading ? "Researching company" : "Research company"}>{loading ? "…" : "→"}</button></div></form><div className="example-links"><span>Explore with</span>{["hubspot.com", "clay.com", "apollo.io"].map((domain) => <button key={domain} disabled={loading} onClick={() => setUrl(`https://${domain}`)}>{domain.replace('.com','').replace('.io','')} ↗</button>)}</div><p className="start-note">One URL. A structured brief.<br />ICP, buyer signals, positioning, and an experiment.</p>{loading && <div role="status" aria-live="polite" className="premium-progress"><p>{loadingStep}<span>{progress}%</span></p><div><i style={{ width: `${progress}%` }} /></div></div>}{error && <p role="alert" className="premium-error">{error}</p>}</div></div>
      </section>
      <section className="product-stage" aria-label="Illustrative research brief">
        <div className="stage-caption"><span>THE RESEARCH WORKSPACE</span><span>ILLUSTRATIVE BRIEF · FICTIONAL COMPANY</span></div>
        <div className="product-window"><aside className="preview-sidebar"><Brand /><p className="workspace-label">RESEARCH WORKSPACE</p><div className="preview-nav active">▦ <span>Company brief</span><span className="nav-shortcut">01</span></div><div className="preview-nav">◎ <span>Account discovery</span><span className="nav-shortcut">02</span></div><div className="preview-nav">≡ <span>Evidence & sources</span><span className="nav-shortcut">03</span></div><div className="preview-sidebar-bottom"><span className="avatar">YH</span><div>Yashika Hemnani<small>Personal workspace</small></div></div></aside>
          <div className="preview-content"><div className="preview-topbar"><span>Research <span className="breadcrumb-slash">/</span> Company brief</span><span className="preview-sample">Sample preview</span></div><div className="preview-body"><div className="brief-heading"><div className="company-monogram">M</div><div><h2>Meridian</h2><p>B2B software · Revenue intelligence</p></div><span className="brief-status"><span />Ready for review</span></div><div className="brief-tabs"><span className="selected">Overview</span><span>Ideal customer</span><span>Buyer signals</span><span>Experiment</span></div><div className="brief-grid"><div className="brief-summary"><p className="preview-label">THE OPPORTUNITY</p><h3>Less research friction.<br />More relevant conversations.</h3><p>Explore how a revenue intelligence product could reach sales teams managing complex account research.</p><div className="brief-tags"><span>Sales operations</span><span>Account research</span><span>Workflow efficiency</span></div></div><div className="signal-panel"><div className="signal-panel-heading"><span>Research dimensions</span><span>05</span></div>{[{name:'ICP fit',width:'86%',color:'#8472eb'},{name:'Buyer relevance',width:'72%',color:'#5b9d87'},{name:'Positioning',width:'79%',color:'#dfa75a'},{name:'Channel fit',width:'64%',color:'#6299c0'},{name:'Experiment clarity',width:'75%',color:'#c68c9e'}].map((item) => <div className="signal-row" key={item.name}><span>{item.name}</span><div><i style={{width:item.width,background:item.color}} /></div></div>)}<p>Illustrative dimensions, not measured results.</p></div></div><div className="brief-lower"><div><span className="small-index">01</span><p>Target buyer<strong>Revenue Operations</strong></p></div><div><span className="small-index">02</span><p>Pain hypothesis<strong>Manual account research</strong></p></div><div><span className="small-index">03</span><p>Next experiment<strong>Test a research-led message</strong></p></div></div></div></div>
        </div>
      </section>
      <section id="method" className="premium-method"><div className="method-intro"><p className="eyebrow">A DELIBERATE WORKFLOW</p><h2>From scattered signals<br />to a <em>clear next step.</em></h2><Link href="/discover">Explore buyer discovery ↗</Link></div><div className="method-rows">{[{n:'01',title:'Understand the business',copy:'Review the company’s positioning, audience, and homepage evidence. Build a hypothesis you can explain.',tag:'Company intelligence',color:'#8472eb'},{n:'02',title:'Qualify the opportunity',copy:'Define target accounts. Prepare a Clay enrichment workflow and review the fit before moving forward.',tag:'Account intelligence',color:'#5b9d87'},{n:'03',title:'Reach the right people',copy:'Find relevant roles with Apollo, review the shortlist, and prepare a measured go-to-market experiment.',tag:'Buyer intelligence',color:'#dfa75a'}].map((item) => <article key={item.n}><span className="method-number">{item.n}</span><div><h3>{item.title}</h3><p>{item.copy}</p><span className="method-tag"><i style={{background:item.color}} />{item.tag}</span></div><span className="method-arrow" aria-hidden="true">↗</span></article>)}</div></section>
      <footer className="premium-footer"><Link href="/" aria-label="GTM Genome home"><Brand /></Link><p>Research with context. Act with intention.</p><a href="https://www.linkedin.com/in/yashika-hemnani-6883b5214/" target="_blank" rel="noreferrer">Built by Yashika Hemnani ↗</a><span>AI-generated insights require review.</span></footer>
    </main>
  );
}
